2023-05-25 11:01:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "CREATE TABLE test_table(name VARCHAR(14), last_name VARCHAR(39)[*]"; ожидалось "ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"
Syntax error in SQL statement "CREATE TABLE test_table(name VARCHAR(14), last_name VARCHAR(39)[*]"; expected "ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
CREATE TABLE test_table(name VARCHAR(14), last_name VARCHAR(39) [42001-214]
2023-05-27 20:46:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Таблица "WORKER" уже существует
Table "WORKER" already exists; SQL statement:
CREATE TABLE worker(
    id IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL CHECK (LENGTH(name) > 2 AND LENGTH(name) <=100),
    birthday DATE NOT NULL CHECK (YEAR(birthday) > 1900),
    level VARCHAR(50) NOT NULL,
    salary_for_a_month INT NOT NULL CHECK(salary_for_a_month > 100 AND salary_for_a_month < 100000)

) [42101-214]
2023-05-27 20:48:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "CREATE TABLE worker [*]IF NOT EXISTS(\000a    id IDENTITY PRIMARY KEY,\000a    name VARCHAR NOT NULL CHECK (LENGTH(name) > 2 AND LENGTH(name) <=100),\000a    birthday DATE NOT NULL CHECK (YEAR(birthday) > 1900),\000a    level VARCHAR(50) NOT NULL,\000a    salary_for_a_month INT NOT NULL CHECK(salary_for_a_month > 100 AND salary_for_a_month < 100000)\000a\000a);\000a\000aALTER TABLE worker\000aADD CONSTRAINT level_values\000aCHECK (level IN ('trainee', 'junior', 'middle', 'senior'));\000a\000aCREATE TABLE client IF NOT EXISTS (\000a    id IDENTITY PRIMARY KEY,\000a    name VARCHAR NOT NULL CHECK (LENGTH(name) > 2 AND LENGTH(name) <=1000)\000a);\000a\000aCREATE TABLE project IF NOT EXISTS(\000a    id IDENTITY PRIMARY KEY,\000a    client_id INT,\000a    start_date DATE,\000a    finish_date DATE\000a);\000a\000aCREATE TABLE project_worker IF NOT EXISTS(\000a    project_id INTEGER,\000a    worker_id INTEGER,\000a    PRIMARY KEY(project_id, worker_id),\000a    FOREIGN KEY(project_id) REFERENCES project(id),\000a    FOREIGN KEY(worker_id) REFERENCES worker(id)\000a);"
Syntax error in SQL statement "CREATE TABLE worker [*]IF NOT EXISTS(\000a    id IDENTITY PRIMARY KEY,\000a    name VARCHAR NOT NULL CHECK (LENGTH(name) > 2 AND LENGTH(name) <=100),\000a    birthday DATE NOT NULL CHECK (YEAR(birthday) > 1900),\000a    level VARCHAR(50) NOT NULL,\000a    salary_for_a_month INT NOT NULL CHECK(salary_for_a_month > 100 AND salary_for_a_month < 100000)\000a\000a);\000a\000aALTER TABLE worker\000aADD CONSTRAINT level_values\000aCHECK (level IN ('trainee', 'junior', 'middle', 'senior'));\000a\000aCREATE TABLE client IF NOT EXISTS (\000a    id IDENTITY PRIMARY KEY,\000a    name VARCHAR NOT NULL CHECK (LENGTH(name) > 2 AND LENGTH(name) <=1000)\000a);\000a\000aCREATE TABLE project IF NOT EXISTS(\000a    id IDENTITY PRIMARY KEY,\000a    client_id INT,\000a    start_date DATE,\000a    finish_date DATE\000a);\000a\000aCREATE TABLE project_worker IF NOT EXISTS(\000a    project_id INTEGER,\000a    worker_id INTEGER,\000a    PRIMARY KEY(project_id, worker_id),\000a    FOREIGN KEY(project_id) REFERENCES project(id),\000a    FOREIGN KEY(worker_id) REFERENCES worker(id)\000a);"; SQL statement:
CREATE TABLE worker IF NOT EXISTS(
    id IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL CHECK (LENGTH(name) > 2 AND LENGTH(name) <=100),
    birthday DATE NOT NULL CHECK (YEAR(birthday) > 1900),
    level VARCHAR(50) NOT NULL,
    salary_for_a_month INT NOT NULL CHECK(salary_for_a_month > 100 AND salary_for_a_month < 100000)

);

ALTER TABLE worker
ADD CONSTRAINT level_values
CHECK (level IN ('trainee', 'junior', 'middle', 'senior'));

CREATE TABLE client IF NOT EXISTS (
    id IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL CHECK (LENGTH(name) > 2 AND LENGTH(name) <=1000)
);

CREATE TABLE project IF NOT EXISTS(
    id IDENTITY PRIMARY KEY,
    client_id INT,
    start_date DATE,
    finish_date DATE
);

CREATE TABLE project_worker IF NOT EXISTS(
    project_id INTEGER,
    worker_id INTEGER,
    PRIMARY KEY(project_id, worker_id),
    FOREIGN KEY(project_id) REFERENCES project(id),
    FOREIGN KEY(worker_id) REFERENCES worker(id)
); [42000-214]
2023-05-27 20:49:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Ограничение "LEVEL_VALUES" уже существует
Constraint "LEVEL_VALUES" already exists; SQL statement:
ALTER TABLE worker
ADD CONSTRAINT level_values
CHECK (level IN ('trainee', 'junior', 'middle', 'senior')) [90045-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:632)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:109)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:72)
	at org.h2.command.ddl.AlterTable.update(AlterTable.java:46)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.command.CommandList.update(CommandList.java:65)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:58)
	at org.h2.command.CommandList.update(CommandList.java:66)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:190)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:143)
	at org.example.Database.executeUpdate(Database.java:34)
	at org.example.sqlCommands.DatabaseInitService.main(DatabaseInitService.java:25)
2023-05-27 20:49:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "ALTER TABLE [*]IF NOT EXISTS worker\000aADD CONSTRAINT level_values\000aCHECK (level IN ('trainee', 'junior', 'middle', 'senior'));\000a\000aCREATE TABLE IF NOT EXISTS client (\000a    id IDENTITY PRIMARY KEY,\000a    name VARCHAR NOT NULL CHECK (LENGTH(name) > 2 AND LENGTH(name) <=1000)\000a);\000a\000aCREATE TABLE IF NOT EXISTS project(\000a    id IDENTITY PRIMARY KEY,\000a    client_id INT,\000a    start_date DATE,\000a    finish_date DATE\000a);\000a\000aCREATE TABLE IF NOT EXISTS project_worker(\000a    project_id INTEGER,\000a    worker_id INTEGER,\000a    PRIMARY KEY(project_id, worker_id),\000a    FOREIGN KEY(project_id) REFERENCES project(id),\000a    FOREIGN KEY(worker_id) REFERENCES worker(id)\000a);"; ожидалось "identifier"
Syntax error in SQL statement "ALTER TABLE [*]IF NOT EXISTS worker\000aADD CONSTRAINT level_values\000aCHECK (level IN ('trainee', 'junior', 'middle', 'senior'));\000a\000aCREATE TABLE IF NOT EXISTS client (\000a    id IDENTITY PRIMARY KEY,\000a    name VARCHAR NOT NULL CHECK (LENGTH(name) > 2 AND LENGTH(name) <=1000)\000a);\000a\000aCREATE TABLE IF NOT EXISTS project(\000a    id IDENTITY PRIMARY KEY,\000a    client_id INT,\000a    start_date DATE,\000a    finish_date DATE\000a);\000a\000aCREATE TABLE IF NOT EXISTS project_worker(\000a    project_id INTEGER,\000a    worker_id INTEGER,\000a    PRIMARY KEY(project_id, worker_id),\000a    FOREIGN KEY(project_id) REFERENCES project(id),\000a    FOREIGN KEY(worker_id) REFERENCES worker(id)\000a);"; expected "identifier"; SQL statement:
ALTER TABLE IF NOT EXISTS worker
ADD CONSTRAINT level_values
CHECK (level IN ('trainee', 'junior', 'middle', 'senior'));

CREATE TABLE IF NOT EXISTS client (
    id IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL CHECK (LENGTH(name) > 2 AND LENGTH(name) <=1000)
);

CREATE TABLE IF NOT EXISTS project(
    id IDENTITY PRIMARY KEY,
    client_id INT,
    start_date DATE,
    finish_date DATE
);

CREATE TABLE IF NOT EXISTS project_worker(
    project_id INTEGER,
    worker_id INTEGER,
    PRIMARY KEY(project_id, worker_id),
    FOREIGN KEY(project_id) REFERENCES project(id),
    FOREIGN KEY(worker_id) REFERENCES worker(id)
); [42001-214]
2023-05-27 20:56:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "[*]TASK 2\000a\000aINSERT INTO worker VALUES\000a    (1, 'Bill', '1986-09-01', 'junior', 2000),\000a    (2, 'Ross', '1992-01-23', 'middle', 5000),\000a    (3, 'Peter', '1987-09-12', 'middle', 5000),\000a    (4, 'Mary', '1992-12-07', 'trainee', 800),\000a    (5, 'Monica', '1991-07-14', 'junior', 2000),\000a    (6, 'Joe', '1979-05-27', 'senior', 30000),\000a    (7, 'Nina', '1990-01-01', 'trainee', 800),\000a    (8, 'Anna', '1985-04-03', 'senior', 35000),\000a    (9, 'Tanya', '1993-07-13', 'senior', 35000),\000a    (10, 'Mark', '1996-08-18', 'trainee', 800);\000a\000a    INSERT INTO client VALUES\000a    (1, 'Clint'),\000a    (2, 'Kate'),\000a    (3, 'Max'),\000a    (4, 'Paul'),\000a    (5, 'Tom');\000a\000a    INSERT INTO project VALUES\000a    (1, 1, '2023-01-25', '2023-05-01'),\000a    (2, 1, '2022-10-01', '2022-12-31'),\000a    (3, 2, '2023-01-13', '2023-04-15'),\000a    (4, 2, '2022-09-21', '2023-01-21'),\000a    (5, 3, '2023-02-27', '2023-05-05'),\000a    (6, 3, '2022-07-13', '2022-12-12'),\000a    (7, 4, '2022-03-25', '2023-03-21'),\000a    (8, 4, '2022-06-01', '2023-02-20'),\000a    (9, 5, '2023-02-13', '2023-04-30'),\000a    (10, 5, '2022-08-02', '2023-05-10');\000a\000aINSERT INTO project_worker VALUES\000a(1, 2), (1, 3),\000a(1, 6),(1, 8),\000a(2, 9),(2, 10),\000a(3, 4),(4, 7),\000a(4, 1),(4, 2),\000a(5, 7),(5, 3),\000a(5, 9),(6, 5),\000a(6, 10),(7, 8),\000a(8, 1),(8, 4),\000a(8, 5),(9, 6),\000a(9, 9),(10, 4),\000a(10, 7),(10, 3);"; ожидалось "TRUNCATE"
Syntax error in SQL statement "[*]TASK 2\000a\000aINSERT INTO worker VALUES\000a    (1, 'Bill', '1986-09-01', 'junior', 2000),\000a    (2, 'Ross', '1992-01-23', 'middle', 5000),\000a    (3, 'Peter', '1987-09-12', 'middle', 5000),\000a    (4, 'Mary', '1992-12-07', 'trainee', 800),\000a    (5, 'Monica', '1991-07-14', 'junior', 2000),\000a    (6, 'Joe', '1979-05-27', 'senior', 30000),\000a    (7, 'Nina', '1990-01-01', 'trainee', 800),\000a    (8, 'Anna', '1985-04-03', 'senior', 35000),\000a    (9, 'Tanya', '1993-07-13', 'senior', 35000),\000a    (10, 'Mark', '1996-08-18', 'trainee', 800);\000a\000a    INSERT INTO client VALUES\000a    (1, 'Clint'),\000a    (2, 'Kate'),\000a    (3, 'Max'),\000a    (4, 'Paul'),\000a    (5, 'Tom');\000a\000a    INSERT INTO project VALUES\000a    (1, 1, '2023-01-25', '2023-05-01'),\000a    (2, 1, '2022-10-01', '2022-12-31'),\000a    (3, 2, '2023-01-13', '2023-04-15'),\000a    (4, 2, '2022-09-21', '2023-01-21'),\000a    (5, 3, '2023-02-27', '2023-05-05'),\000a    (6, 3, '2022-07-13', '2022-12-12'),\000a    (7, 4, '2022-03-25', '2023-03-21'),\000a    (8, 4, '2022-06-01', '2023-02-20'),\000a    (9, 5, '2023-02-13', '2023-04-30'),\000a    (10, 5, '2022-08-02', '2023-05-10');\000a\000aINSERT INTO project_worker VALUES\000a(1, 2), (1, 3),\000a(1, 6),(1, 8),\000a(2, 9),(2, 10),\000a(3, 4),(4, 7),\000a(4, 1),(4, 2),\000a(5, 7),(5, 3),\000a(5, 9),(6, 5),\000a(6, 10),(7, 8),\000a(8, 1),(8, 4),\000a(8, 5),(9, 6),\000a(9, 9),(10, 4),\000a(10, 7),(10, 3);"; expected "TRUNCATE"; SQL statement:
TASK 2

INSERT INTO worker VALUES
    (1, 'Bill', '1986-09-01', 'junior', 2000),
    (2, 'Ross', '1992-01-23', 'middle', 5000),
    (3, 'Peter', '1987-09-12', 'middle', 5000),
    (4, 'Mary', '1992-12-07', 'trainee', 800),
    (5, 'Monica', '1991-07-14', 'junior', 2000),
    (6, 'Joe', '1979-05-27', 'senior', 30000),
    (7, 'Nina', '1990-01-01', 'trainee', 800),
    (8, 'Anna', '1985-04-03', 'senior', 35000),
    (9, 'Tanya', '1993-07-13', 'senior', 35000),
    (10, 'Mark', '1996-08-18', 'trainee', 800);

    INSERT INTO client VALUES
    (1, 'Clint'),
    (2, 'Kate'),
    (3, 'Max'),
    (4, 'Paul'),
    (5, 'Tom');

    INSERT INTO project VALUES
    (1, 1, '2023-01-25', '2023-05-01'),
    (2, 1, '2022-10-01', '2022-12-31'),
    (3, 2, '2023-01-13', '2023-04-15'),
    (4, 2, '2022-09-21', '2023-01-21'),
    (5, 3, '2023-02-27', '2023-05-05'),
    (6, 3, '2022-07-13', '2022-12-12'),
    (7, 4, '2022-03-25', '2023-03-21'),
    (8, 4, '2022-06-01', '2023-02-20'),
    (9, 5, '2023-02-13', '2023-04-30'),
    (10, 5, '2022-08-02', '2023-05-10');

INSERT INTO project_worker VALUES
(1, 2), (1, 3),
(1, 6),(1, 8),
(2, 9),(2, 10),
(3, 4),(4, 7),
(4, 1),(4, 2),
(5, 7),(5, 3),
(5, 9),(6, 5),
(6, 10),(7, 8),
(8, 1),(8, 4),
(8, 5),(9, 6),
(9, 9),(10, 4),
(10, 7),(10, 3); [42001-214]
2023-05-27 21:55:59 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.example.Database.<init>(Database.java:20)
	at org.example.Database.<clinit>(Database.java:12)
	at org.example.sqlCommands.DatabaseQueryService.main(DatabaseQueryService.java:17)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 14 more
2023-05-27 21:56:14 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.example.Database.<init>(Database.java:20)
	at org.example.Database.<clinit>(Database.java:12)
	at org.example.sqlCommands.DatabaseQueryService.main(DatabaseQueryService.java:17)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 14 more
2023-05-27 21:56:46 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.example.Database.<init>(Database.java:20)
	at org.example.Database.<clinit>(Database.java:12)
	at org.example.sqlCommands.DatabasePopulateService.main(DatabasePopulateService.java:13)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 14 more
2023-05-27 21:57:21 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.example.Database.<init>(Database.java:20)
	at org.example.Database.<clinit>(Database.java:12)
	at org.example.sqlCommands.DatabaseQueryService.main(DatabaseQueryService.java:17)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 14 more
2023-05-27 21:57:46 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.example.Database.<init>(Database.java:20)
	at org.example.Database.<clinit>(Database.java:12)
	at org.example.sqlCommands.DatabaseQueryService.main(DatabaseQueryService.java:17)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 14 more
2023-05-27 21:58:32 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.example.Database.<init>(Database.java:20)
	at org.example.Database.<clinit>(Database.java:12)
	at org.example.sqlCommands.DatabaseQueryService.main(DatabaseQueryService.java:17)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 14 more
2023-05-27 21:59:28 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.example.Database.<init>(Database.java:20)
	at org.example.Database.<clinit>(Database.java:12)
	at org.example.sqlCommands.DatabaseQueryService.main(DatabaseQueryService.java:16)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 14 more
2023-05-27 22:13:49 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.example.Database.<init>(Database.java:20)
	at org.example.Database.<clinit>(Database.java:12)
	at org.example.sqlCommands.DatabaseQueryService.main(DatabaseQueryService.java:19)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 20 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 14 more
2023-05-27 22:49:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Синтаксическая ошибка в выражении SQL "[*]TASK 6\000a\000aSELECT 'YOUNGEST' AS type, name, birthday\000aFROM worker\000aWHERE birthday = (SELECT MAX(birthday) FROM worker)\000aUNION\000aSELECT 'ELDEST' AS type, name, birthday\000aFROM worker\000aWHERE birthday = (SELECT MIN(birthday) FROM worker);"; ожидалось "TRUNCATE"
Syntax error in SQL statement "[*]TASK 6\000a\000aSELECT 'YOUNGEST' AS type, name, birthday\000aFROM worker\000aWHERE birthday = (SELECT MAX(birthday) FROM worker)\000aUNION\000aSELECT 'ELDEST' AS type, name, birthday\000aFROM worker\000aWHERE birthday = (SELECT MIN(birthday) FROM worker);"; expected "TRUNCATE"; SQL statement:
TASK 6

SELECT 'YOUNGEST' AS type, name, birthday
FROM worker
WHERE birthday = (SELECT MAX(birthday) FROM worker)
UNION
SELECT 'ELDEST' AS type, name, birthday
FROM worker
WHERE birthday = (SELECT MIN(birthday) FROM worker); [42001-214]
2023-05-27 22:57:56 database: flush
org.h2.message.DbException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.example.Database.<init>(Database.java:20)
	at org.example.Database.<clinit>(Database.java:12)
	at org.example.sqlCommands.DatabaseQueryService.<clinit>(DatabaseQueryService.java:16)
	at org.example.TestsDB.main(TestsDB.java:13)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Внутренняя ошибка: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]"
General error: "org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 21 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: /Users/Tanya/modul-4-dev/testH2.mv.db [2.1.214/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:178)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 15 more
2023-06-07 11:05:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Объект уже закрыт
The object is already closed [90007-214]
2023-06-07 11:05:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Объект уже закрыт
The object is already closed [90007-214]
2023-06-07 11:17:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Объект уже закрыт
The object is already closed [90007-214]
2023-06-07 11:20:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLNonTransientException: Объект уже закрыт
The object is already closed [90007-214]
2023-06-07 11:32:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Неверное количество столбцов
Column count does not match; SQL statement:
INSERT INTO project VALUES(?, ?) [21002-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.command.dml.Insert.doPrepare(Insert.java:295)
	at org.h2.command.dml.DataChangeStatement.prepare(DataChangeStatement.java:37)
	at org.h2.command.Parser.prepareCommand(Parser.java:575)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at org.example.sqlCommands.MyPreparedStatement.<init>(MyPreparedStatement.java:22)
	at org.example.TestsDB.main(TestsDB.java:14)
2023-06-07 12:21:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Неверное количество столбцов
Column count does not match; SQL statement:
INSERT INTO project VALUES (?, ?, ?) [21002-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.command.dml.Insert.doPrepare(Insert.java:295)
	at org.h2.command.dml.DataChangeStatement.prepare(DataChangeStatement.java:37)
	at org.h2.command.Parser.prepareCommand(Parser.java:575)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:631)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:554)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at org.example.sqlCommands.MyPreparedStatement.<init>(MyPreparedStatement.java:24)
	at org.example.TestsDB.main(TestsDB.java:14)
